
CREATE PROCEDURE [dbo].[SP_List_Seguridad]
	@ID_TipoUsuario [int]

AS

SELECT M.ID_MENU, 
      NODOID, 
      [NAME], 
      CAPTION, 
      PARENTID, 
      ORDEN, 
	  CAST(CASE WHEN MTD.ID_MENU IS NULL THEN 0 ELSE 1 END AS BIT) AUTORIZACION 
FROM MENU M
LEFT JOIN MENUTIPOSUSUARIO MTD ON MTD.ID_MENU = M.ID_MENU AND MTD.ID_TIPOUSUARIO = @ID_TipoUsuario
ORDER BY ORDEN
